import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  smallbutton: {
    backgroundColor: '#FBB017',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'white',
    width: 100,
    height: 50,
    paddingTop: 10,
  },
  mediumbutton: {
    backgroundColor: '#FBB017',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'white',
    width: 250,
    height: 50,
    paddingTop: 7,
  },
  largebutton: {
    backgroundColor: '#FBB017',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'white',
    width: 300,
    height: 50,
    padding: 10,
  },
  buttonText: {
    color: '#FFFFFF',
    fontFamily: 'OpenSans-Italic-VariableFont_wdth,wght',
    fontSize: 20,
    textAlign: 'center',
    fontWeight: '700',
  },
  buttonTextYellow: {
    color: '#FBB017',
    fontFamily: 'OpenSans-Italic-VariableFont_wdth,wght',
    fontSize: 20,
    textAlign: 'center',
    fontWeight: '700',
  },
  buttonTextRed: {
    color: '#E63946',
    fontFamily: 'OpenSans-Italic-VariableFont_wdth,wght',
    fontSize: 20,
    textAlign: 'center',
    fontWeight: '700',
  },
  buttonTextBlue: {
    color: '#1E90FF',
    fontFamily: 'OpenSans-Italic-VariableFont_wdth,wght',
    fontSize: 20,
    textAlign: 'center',
    fontWeight: '700',
  },
  smallbuttonwhite: {
    backgroundColor: '#ffffff',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'white',
    width: 100,
    height: 35,
    padding: 2,
  },
  smallbuttonpurple: {
    backgroundColor: '#5E50A1',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'white',
    width: 100,
    height: 35,
    padding: 2,
  },
  smallbuttonred: {
    backgroundColor: '#E63946',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'white',
    width: 100,
    height: 35,
    padding: 2,
  },
  mediumbuttonwhite: {
    backgroundColor: '#ffffff',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'white',
    width: 200,
    height: 40,
    padding: 5,
  },
  mediumbuttonpurple: {
    backgroundColor: '#5E50A1',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'white',
    width: 200,
    height: 40,
    padding: 5,
  },
  largebuttonwhite: {
    backgroundColor: '#ffffff',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'white',
    width: 300,
    height: 50,
    padding: 10,
  },
  largebuttonpurple: {
    backgroundColor: '#5E50A1',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'white',
    width: 300,
    height: 50,
    padding: 10,
  },
  buttonTextpurple: {
    color: '#5E50A1',
    fontFamily: 'OpenSans-Italic-VariableFont_wdth,wght',
    fontSize: 20,
    textAlign: 'center',
    fontWeight: '700',
  },
  smallbuttontransparent: {
    backgroundColor: 'none',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'white',
    width: 100,
    height: 35,
    padding: 2,
  },
  smalltransparentpurple: {
    backgroundColor: 'none',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#5E50A1',
    width: 100,
    height: 35,
    padding: 2,
  },
  mediumbuttontransparent: {
    backgroundColor: 'none',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'white',
    width: 200,
    height: 40,
    padding: 5,
  },
  mediumtransparentyellow: {
    backgroundColor: 'none',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#FBB017',
    width: 250,
    height: 40,
    padding: 5,
  },
  mediumtransparentred: {
    backgroundColor: 'none',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#E63946',
    width: 250,
    height: 40,
    padding: 5,
  },
  mediumtransparentblue: {
    backgroundColor: 'none',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#1E90FF',
    width: 250,
    height: 40,
    padding: 5,
  },
  mediumtransparentpurple: {
    backgroundColor: 'none',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#5E50A1',
    width: 200,
    height: 40,
    padding: 5,
  },
  largebuttontransparent: {
    backgroundColor: 'none',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'white',
    width: 300,
    height: 50,
    padding: 10,
  },
  largetransparentpurple: {
    backgroundColor: 'none',
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#5E50A1',
    width: 300,
    height: 50,
    padding: 10,
  },
});
